### ISSUE TITLE
Subscription form confirmation not visible

### ISSUE THREAD

**Issue by mburridge** [WordPress/wporg-developer-blog#14] opened 2022-10-26 15:35 UTC
If the Subscription Form block is placed further down the page (as it is at [developer.wordpress.org/news](https://developer.wordpress.org/news/)) the success/failure confirmation message appears in the same place when the page is refreshed after submission. This necessitates the user having to scroll to see the confirmation message.

Ideally, on page refresh after submission:
- the page should auto-scroll to the location of the confirmation message, or
- the confirmation message should appear in a 'status bar' at the top of the screen, or
- other behaviour that makes the confirmation message obvious to the user.

In either case some JS should be enqueued that targets the `.jetpack_subscription_widget` `.success` or `.error` div.

<img width="402" alt="image" src="https://user-images.githubusercontent.com/20643925/198069612-723182ee-bb77-4789-a8e2-e44f67b4a7b9.png">

<img width="402" alt="image" src="https://user-images.githubusercontent.com/20643925/198069860-31839139-4345-477a-ae87-380605ee4170.png">

**Comment by ryelle** [comment] 2022-10-26 16:08
I've marked this "On Hold" since ideally this will be fixed in Jetpack. If the developer blog still needs some custom code this status can be removed.

**Comment by mburridge** [comment] 2022-10-26 16:15
I don't know what kind of time scale we might be looking at to get this fixed in Jetpack. If it's going to be quite some time then I think in the interim it would be good to just have some simple JS enqueued in the developer blog that scrolls to the location of the form if either the `.success` or `.error` classes exist.

**Comment by mburridge** [comment] 2022-10-26 16:17
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

**Comment by mburridge** [comment] 2022-10-26 16:25
Not tested, but something like this enqueued from the theme's `functions.php` should do it.

```
let success = document.getElementsByClassName('success')
let error = document.getElementsByClassName('error')

if (success.length || error.length) {
    document.querySelector('.jetpack_subscription_widget').scrollIntoView(alignToTop)
}

**Comment by bph** [comment] 2022-10-26 22:58
I am experimenting with the subscription form next to the search form. For now only on the front page... What do you think? Needs some minor design tweaks, though. 
![Screen Shot 2022-10-26 at 14 44 44](https://user-images.githubusercontent.com/39980/198154188-29cfbfce-f697-4b5f-bfb1-8e361c99ed34.png)

**Comment by ice9js** [comment] 2022-10-27 14:51
After looking into it a bit, it seems developer.wordpress.org might be using an outdated version of Jetpack.  
Particularly, I noticed the form ID doesn't match the value in the `redirect_fragment` input which results in an incorrect redirect link when the form is submitted, causing the page not to focus on the form.

I believe the issues described here should already have been fixed in [Automattic/jetpack#21067](https://github.com/Automattic/jetpack/pull/21067).

**Comment by kraftbj** [comment] 2022-10-27 16:13
In terms of timeline, Jetpack's updates are being blocked due to some hardcoded file paths in the Plugin Directory that changed, but I hadn't spent the effort to get it resolved until now :-(.

https://github.com/WordPress/wordpress.org/pull/103 would remove the blocker so I can push forward with the Jetpack upgrade.

**Comment by ryelle** [comment] 2022-10-31 16:11
Jetpack has been updated on WordPress.org, and the form focus issue seems to be fixed now 👍🏻 

Thanks to @kraftbj and @dd32 for getting wporg updated!

**Closed as completed by ryelle** 2022-10-31 16:11 UTC
Labels: [Status] On Hold

**Comment by bph** [comment] 2022-10-31 17:57
I can confirm. The subscription form is fixed. 

https://user-images.githubusercontent.com/39980/199076487-9244a200-30db-4be6-abe9-72189853f8a0.mp4

Thank you to @dd32 @kraftbj @ice9js @mburridge to collaborate on the fix so fast!

**Comment by mburridge** [comment] 2022-10-31 18:39
Tested and confirmed as working as desired. Thank you @ryelle .
