### ISSUE TITLE
Social Image and other Meta tags need review

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#18] opened 2022-11-19 22:01 UTC
I shared a post on Slack, and it noticed a featured image but couldn't display it. 
![Screen Shot 2022-11-19 at 16 59 21](https://user-images.githubusercontent.com/39980/202873089-254b591c-44d4-439b-95b7-4fb114a4e826.png)
When I clicked on the image, it showed it in full-page view. (see video)

https://user-images.githubusercontent.com/39980/202873125-cccd8b00-c6d1-46a9-8c61-673fdcb63ccf.mp4

**Comment by bph** [comment] 2022-11-19 22:06
It wouldn't work with Twitter either. 
![Screen Shot 2022-11-19 at 17 06 00](https://user-images.githubusercontent.com/39980/202873257-189d72ec-2e78-4da9-8e66-fa2c8ecd7a05.png)

Must have botched the set-up of the Social Image plugin...

**Comment by bph** [comment] 2022-11-21 22:59
It seems to work when a page is shared on Discord 
![Screenshot_20221121-175739](https://user-images.githubusercontent.com/39980/203174900-43f3ab1f-6f18-4277-a2c0-fe535559d986.png)

**Comment by justintadlock** [comment] 2022-12-07 22:32
Twitter currently only seems to be recognizing `og:title` or `twitter:title` meta fields when building its cards.  Unlike Facebook and other places, it's not grabbing the "card title" from `<title>` in the `<head>` area.  If both of the meta fields are missing, the card isn't getting generated.

![tweet-title](https://user-images.githubusercontent.com/1816309/206311030-7ea17850-a25f-4660-ba65-de1b11941c08.jpg)

**Comment by outdoor2kode** [comment] 2023-01-19 10:25
@bph Could you test these platforms again to see if the issues are still there? I seem able to see the image review for all of them. Thanks.

#### Slack
<img width="433" alt="image" src="https://user-images.githubusercontent.com/18050944/213410317-d09a4831-830c-49e4-9117-4eab46546828.png">

#### Twitter
![image](https://user-images.githubusercontent.com/18050944/213410593-e04b9af3-7909-426f-9e23-1f38fc03a7f1.png)

#### Discord
![image](https://user-images.githubusercontent.com/18050944/213411171-8331a902-9443-42b1-ab01-fef9fd1957af.png)

**Comment by outdoor2kode** [comment] 2023-01-19 10:28
> Twitter currently only seems to be recognizing og:title or twitter:title meta fields when building its cards. Unlike Facebook and other places, it's not grabbing the "card title" from <title> in the <head> area. If both of the meta fields are missing, the card isn't getting generated.

It seems that the [validator](https://cards-dev.twitter.com/validator) doesn't work anymore, even their own [example site](https://blog.twitter.com/official/en_us/a/2015/history-of-tbt-on-twitter.html) introduced in their [docs](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image) couldn't show the card preview successfully.

**Update:** It seems that Twitter doesn't always show the image previews for our news posts (it would always show the preview cards correctly for other sites once pasting links on the tweet box (e.g., wp.org)), I've tried several times for some extra testings, it didn't show anymore. Not sure if it's the case for you?

I'll go ahead and add the specified meta tags first as instructed [here](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image).

**Comment by bph** [comment] 2023-01-19 11:02
Thanks for looking into this. @renintw 
Just for confirmation, it seems the validator requires an `og:title` meta tag explicitly using the title of the post. I look through the header information and I couldn't find it. 

<img width="1087" alt="Screenshot 2023-01-19 at 12 00 41" src="https://user-images.githubusercontent.com/39980/213425556-68b776d4-22a7-44e2-b9af-18bb82a291a6.png">

**Comment by outdoor2kode** [comment] 2023-01-19 13:08
@bph yeah, `og:title` hasn't been added to our news pages yet, and the validator you were using doesn't seem to work correctly anymore even if `og:title` or any required meta tags are provided, so the results might not be 100% reliable. 
But I'm curious if it would show the img preview on twitter or slack now on your side? Or it's still displaying fallback img.

**Comment by outdoor2kode** [comment] 2023-01-19 14:04
@ryelle I can see that the meta tags seem to be generated by **social image generator**, 
![image](https://user-images.githubusercontent.com/18050944/213458316-155dfd2f-8ca9-4092-ac86-2460ac469f95.png)

and I did see it's installed on the developer-blog on production, but there are no related settings about meta tags or so. 
#### Social Image Generator
![image](https://user-images.githubusercontent.com/18050944/213458572-738f7b0d-87dc-4507-9e1d-354aef011cb3.png)

I also tried installing it locally, but there wasn't one being found on the plugins download pages. After looking into it further, just realized that it was [acquired](https://socialimagegenerator.com/) by us and integrated into the jetpack.

I'm wondering what's the best action to take next step? It seems that on the production, it still used the **social image generator** rather than **Jetpack**,  and Jetpack seems to have dedicated functions for [twitter card](https://github.com/Automattic/jetpack/blob/a771e30f12f0001e42492ee20d2a208d184f89e2/projects/plugins/jetpack/class.jetpack-twitter-cards.php) and other social media, is it a good idea to replace it with Jetpack?

**Update:** Just Found [this](https://github.com/WordPress/wporg-developer/blob/ec6722b8aac9827a3a4086f19a52d2dd72635514/source/wp-content/themes/wporg-developer-2023/inc/head.php#L100), the way wporg-developer handled the meta tags, it has also deactivated the **social image generator**.

**Comment by ryelle** [comment] 2023-01-19 14:35
> I'm wondering what's the best action to take next step? It seems that on the production, it still used the social image generator rather than Jetpack, and Jetpack seems to have dedicated functions for [twitter card](https://github.com/Automattic/jetpack/blob/a771e30f12f0001e42492ee20d2a208d184f89e2/projects/plugins/jetpack/class.jetpack-twitter-cards.php) and other social media, is it a good idea to replace it with Jetpack?

I'm pretty sure (though correct me if I'm wrong, @bph) that the social image generator was chosen because it created images per post, while Jetpack uses the featured image or a default.

> Update: Just Found [this](https://github.com/WordPress/wporg-developer/blob/ec6722b8aac9827a3a4086f19a52d2dd72635514/source/wp-content/themes/wporg-developer-2023/inc/head.php#L100), the way wporg-developer handled the meta tags, it has also deactivated the social image generator.

If Jetpack is not providing these values, then yeah I'd use this approach. But keep the social image generator.

**Comment by bph** [comment] 2023-01-19 21:20
Yes, @ryelle is correct, we selected the social image generator to have not to worry about featured images for our posts and provide a unified look to the social sharing. The design of the template could use a professional designer's touch but that's out of the scope of this ticket, and changes there can be handled via the plugin's interface. 

Thanks for all your research @renintw and your fixing things 🥇

**Comment by outdoor2kode** [comment] 2023-02-07 09:55
Required SEO tags were added and it's now live in production.

I've tested the first 5 featured posts on the [homepage](https://developer.wordpress.org/news/), and both Slack and Twitter showed all the preview images of the posts. However, while you're testing, you may find that the Slack preview images remain [broken](https://user-images.githubusercontent.com/39980/202873089-254b591c-44d4-439b-95b7-4fb114a4e826.png) or that Twitter still [doesn't show](https://github.com/WordPress/wporg-developer-blog/issues/18#issuecomment-1320979657) the preview image. 

That's mainly caused by caching from Twitter - Cards data continues to be cached for up to 7 days before being refreshed. ([ref](https://twittercommunity.com/t/card-validator-preview-removal/175006)) That being said, there is still something we can do to update the cache. Here are the steps:

1. Provide a “hint” to the cards crawler to revisit your site in [the validator](https://cards-dev.twitter.com/validator), by adding a unique parameter to the URL. Example:
<img width="433" alt="image" src="https://user-images.githubusercontent.com/18050944/217209655-2e68d48f-f224-4e05-b0f3-a3b17e0badf7.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/18050944/217209975-4e3c6e29-0d4f-49c7-81e1-65501a6725a7.png">

Sometimes this would work without really publishing the tweet - the preview images would show up and you can even just directly remove the extra added parameter and still see the preview. But sometimes you need to really tweet it and refresh the page to get it to work.

2. After the above step, go to the menu bar of Slack, **Help** -> **Troubleshooting** -> **Clear Cache and Restart**, then share posts in a channel. The preview image should no longer be broken.

I'll leave this issue open for people to do double-checks. If there's no further issue, feel free to close it.

cc @bph

**Comment by bph** [comment] 2023-02-07 12:55
Thank you so much for moving your fix into production. 
I tested twitter ... 
<img width="603" alt="Screenshot 2023-02-07 at 13 48 45" src="https://user-images.githubusercontent.com/39980/217249239-1f87009a-f91f-44c9-bdcb-5b6d91b8f2f7.png">
Another page: 
<img width="597" alt="Screenshot 2023-02-07 at 13 51 58" src="https://user-images.githubusercontent.com/39980/217249982-53144d0b-ebac-4728-bccc-4e49ed5dc03a.png">


... and Slack. 
<img width="844" alt="Screenshot 2023-02-07 at 13 43 55" src="https://user-images.githubusercontent.com/39980/217249383-69bca0ec-2e09-435e-b55d-f81d0d85b6ef.png">

Seems to be working well, now!

**Closed as completed** 2023-02-07 13:42 UTC
Labels: [Component] Templates, [Component] Backend
